Feature/submodule
CogComp/wikidump-preprocessing pull request #2
Opened 2019-10-14 04:48 UTC by xrhan

2019-10-14 15:05 UTC, nitishgupta commented on makefile
> +WIKIEXTRACTOR = "${MAKEFILEDIR}/wikiextractor/WikiExtractor.py"
Is it necessary to get MAKEFILEDIR? Since the submodule will be directly inside the main repo dir, won't the path simply be `wikiextractor/WikiExtractor.py`. I might be wrong.

2019-10-16 03:27 UTC, xrhan commented on makefile
> +WIKIEXTRACTOR = "${MAKEFILEDIR}/wikiextractor/WikiExtractor.py"
Hmm, I tried the relative path and it doesn't work. PWD also does not work, since there is no guarantee that make is invoked in the same directory as the one that makefile lives in. So I followed the advice from https://stackoverflow.com/questions/18136918/how-to-get-current-relative-directory-of-your-makefile

2019-10-16 03:30 UTC, nitishgupta commented on makefile
> +WIKIEXTRACTOR = "${MAKEFILEDIR}/wikiextractor/WikiExtractor.py"
Okay; looks good to me.

2019-10-16 03:30 UTC, nitishgupta approved these changes

2019-10-16 03:31 UTC, nitishgupta commented on makefile
> +WIKIEXTRACTOR = "${MAKEFILEDIR}/wikiextractor/WikiExtractor.py"
@HeglerTissot please approve at your convenience.

2019-10-16 12:57 UTC, HeglerTissot requested changes
Can't we really have a distinct version of makefile that does not require the sed lines replacing "Users\/nicolette\/Documents" ? That sound like a patchwork when exposing CCG packages.

2019-10-16 13:17 UTC, nitishgupta commented
Yes, that is happening in the other branch. This merger is only for the git
submodule.

On Wed, Oct 16, 2019, 8:57 AM Hegler Tissot <notifications@github.com>
wrote:

> *@HeglerTissot* requested changes on this pull request.
>
> Can't we really have a distinct version of makefile that does not require
> the sed lines replacing "Users/nicolette/Documents" ? That sound like a
> patchwork when exposing CCG packages.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/CogComp/wikidump-preprocessing/pull/2?email_source=notifications&email_token=ABPPK3IEGLTLUMHRQASCYQTQO4FSZA5CNFSM4JAKQEP2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCIEJJEA#pullrequestreview-302552208>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABPPK3MUQQJVKAVVFJDHY6LQO4FSZANCNFSM4JAKQEPQ>
> .
>

2019-10-16 13:24 UTC, HeglerTissot approved these changes

2019-10-16 19:43 UTC, merged